#!/usr/bin/env bash
# Copy the R2_* lines from .env into supabase/functions/.env, which
# `supabase functions serve` auto-loads. Both files are gitignored.
# Re-run after changing any R2_* value in .env (or: npm run functions:env).
set -euo pipefail

cd "$(dirname "$0")/.."

[ -f .env ] || { echo "ERROR: .env not found — run scripts/setup.sh first" >&2; exit 1; }

{
  echo "# Generated by scripts/sync-function-env.sh — edit .env instead."
  grep '^R2_' .env || true
} > supabase/functions/.env

count=$(grep -c '^R2_' supabase/functions/.env || true)
echo "==> supabase/functions/.env written ($count R2_* vars)"
if [ "$count" -eq 0 ]; then
  echo "WARNING: no R2_* vars found in .env — the r2-presign function won't work until they are set" >&2
fi
