#!/usr/bin/env bash
# Write supabase/functions/.env, which `supabase functions serve`
# auto-loads. STORAGE_DRIVER=local always applies to the local stack —
# r2-presign then talks to the local Supabase Storage buckets declared in
# supabase/config.toml instead of Cloudflare R2, so no R2 secrets are needed
# to develop locally (see TODO.md for switching production to STORAGE_DRIVER=r2).
# Any R2_* lines in .env are copied through too, only needed if you're
# testing the r2 driver locally against real R2 credentials.
# Both files are gitignored. Re-run after changing .env (or: npm run functions:env).
set -euo pipefail

cd "$(dirname "$0")/.."

{
  echo "# Generated by scripts/sync-function-env.sh — edit .env instead."
  echo "STORAGE_DRIVER=local"
  echo "LOCAL_PUBLIC_URL=http://127.0.0.1:54321"  # supabase/config.toml [api] port
  [ -f .env ] && grep '^R2_' .env || true
} > supabase/functions/.env

echo "==> supabase/functions/.env written (STORAGE_DRIVER=local)"
